import type {
  CreateWishDTO,
  MemberDTO,
  ReserveDTO,
  UpdateWishDTO,
  WishDTO,
} from '../dto'
import { CreateWishSchema, ReserveSchema, UpdateWishSchema } from '../schemas'

function isReadonly(): boolean {
  return import.meta.env.VITE_READONLY === 'true'
}

function apiUrl(): string {
  return import.meta.env.VITE_API_URL
}

const JSON_HEADERS = { 'Content-Type': 'application/json' }

// Optional shared bearer token for a self-hosted API (`VITE_API_TOKEN`). Empty
// (the default, and always the case for the json-server dev backend and the
// read-only demo) means no Authorization header is sent.
function headers(): Record<string, string> {
  const token = import.meta.env.VITE_API_TOKEN
  return token
    ? { ...JSON_HEADERS, Authorization: `Bearer ${token}` }
    : JSON_HEADERS
}

/**
 * Resolve a resource endpoint.
 *
 * - read/write mode: `<VITE_API_URL>/<name>` — a json-server REST collection.
 * - read-only mode (GitHub Pages): `<BASE_URL><name>.json` — a static file
 *   generated by `npm run db:generate:pages`, served from the app's subpath.
 */
export function resourceUrl(name: string): string {
  return isReadonly()
    ? `${import.meta.env.BASE_URL}${name}.json`
    : `${apiUrl()}/${name}`
}

export async function getMembers(): Promise<MemberDTO[]> {
  return fetch(resourceUrl('members'), { headers: headers() }).then((res) =>
    res.json(),
  )
}

export async function getWishes(): Promise<WishDTO[]> {
  return fetch(resourceUrl('wishes'), { headers: headers() }).then((res) =>
    res.json(),
  )
}

export async function postWish(input: CreateWishDTO): Promise<WishDTO> {
  if (isReadonly()) {
    return Promise.reject(new Error('postWish is disabled in read-only mode'))
  }

  const result = CreateWishSchema.safeParse(input)
  if (!result.success) {
    return Promise.reject(result.error)
  }

  const body = {
    ...result.data,
    createdAt: new Date().toISOString(),
    reservedBy: null,
    reservedAt: null,
  }

  return fetch(resourceUrl('wishes'), {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify(body),
  }).then((res) => res.json())
}

export async function putWish(input: UpdateWishDTO): Promise<WishDTO> {
  if (isReadonly()) {
    return Promise.reject(new Error('putWish is disabled in read-only mode'))
  }
  const { data, success, error } = UpdateWishSchema.safeParse(input)
  if (!success) {
    return Promise.reject(error)
  }

  return fetch(`${resourceUrl('wishes')}/${input.id}`, {
    method: 'PATCH',
    headers: headers(),
    body: JSON.stringify(data),
  }).then((res) => res.json())
}

export async function deleteWish(id: string): Promise<void> {
  if (isReadonly()) {
    return Promise.reject(new Error('deleteWish is disabled in read-only mode'))
  }

  await fetch(`${resourceUrl('wishes')}/${id}`, {
    method: 'DELETE',
    headers: headers(),
  })
}

export async function reserveWish(input: ReserveDTO): Promise<WishDTO> {
  if (isReadonly()) {
    return Promise.reject(
      new Error('reserveWish is disabled in read-only mode'),
    )
  }

  const { data, success, error } = ReserveSchema.safeParse(input)
  if (!success) {
    return Promise.reject(error)
  }

  return fetch(`${resourceUrl('wishes')}/${data.id}`, {
    method: 'PATCH',
    headers: headers(),
    body: JSON.stringify({
      reservedBy: data.reservedBy,
      reservedAt: data.reservedBy ? new Date().toISOString() : null,
    }),
  }).then((res) => res.json())
}
